spring.application.name=NanoURL

spring.datasource.url=jdbc:mysql://localhost:3306/Urlshortnerdb
spring.datasource..username=root
spring.datasource.password=Pratik@9595

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=9c449edf1d2f056790c6a2447ce8ebc1dbe0f386a1a22d7f22275d7725824ea1
jwt.expiration=172800000

frontend.url = http://localhost:5173